import { Job, WorkerProfile, Payment, CalendarEvent } from "@/types";

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Construction Helper Needed",
    description: "Need experienced construction workers for residential project. Must have basic tools.",
    employerId: "emp1",
    employerName: "Sharma Constructions",
    location: "Sector 62, Noida",
    coordinates: { lat: 28.6139, lng: 77.2090 },
    payAmount: 500,
    payType: "daily",
    duration: "15 days",
    requiredSkills: ["Construction", "Physical Strength", "Tool Handling"],
    status: "open",
    teamRequired: true,
    teamSize: 5,
    postedDate: "2025-11-24",
    startDate: "2025-11-27",
    verified: true,
  },
  {
    id: "2",
    title: "Delivery Partners - Urgent",
    description: "E-commerce delivery partners needed. Own vehicle required.",
    employerId: "emp2",
    employerName: "QuickDeliver India",
    location: "Connaught Place, Delhi",
    coordinates: { lat: 28.6304, lng: 77.2177 },
    payAmount: 50,
    payType: "hourly",
    duration: "Flexible",
    requiredSkills: ["Driving", "Navigation", "Customer Service"],
    status: "open",
    teamRequired: false,
    postedDate: "2025-11-25",
    startDate: "2025-11-26",
    verified: true,
  },
  {
    id: "3",
    title: "Plumbing Work - Residential Complex",
    description: "Skilled plumber needed for bathroom renovation work.",
    employerId: "emp3",
    employerName: "Home Services Pro",
    location: "Koramangala, Bangalore",
    coordinates: { lat: 12.9352, lng: 77.6245 },
    payAmount: 8000,
    payType: "fixed",
    duration: "3 days",
    requiredSkills: ["Plumbing", "Pipe Fitting", "Problem Solving"],
    status: "open",
    teamRequired: false,
    postedDate: "2025-11-23",
    startDate: "2025-11-28",
    verified: true,
  },
  {
    id: "4",
    title: "Painting Team Required",
    description: "Need painting team for commercial office space. 5000 sq ft area.",
    employerId: "emp1",
    employerName: "Sharma Constructions",
    location: "Gurgaon Cyber City",
    coordinates: { lat: 28.4595, lng: 77.0266 },
    payAmount: 600,
    payType: "daily",
    duration: "7 days",
    requiredSkills: ["Painting", "Teamwork", "Quality Work"],
    status: "open",
    teamRequired: true,
    teamSize: 4,
    postedDate: "2025-11-25",
    startDate: "2025-12-01",
    verified: true,
  },
];

export const mockWorkers: WorkerProfile[] = [
  {
    id: "w1",
    name: "Rajesh Kumar",
    email: "rajesh@example.com",
    phone: "+91 98765 43210",
    role: "worker",
    skills: ["Construction", "Painting", "Physical Strength"],
    location: "Noida, UP",
    hourlyRate: 60,
    dailyRate: 550,
    bio: "10 years experience in construction. Reliable and hardworking.",
    workPhotos: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400"],
    rating: 4.8,
    completedJobs: 156,
    streak: 12,
    level: "gold",
    totalEarnings: 450000,
    verified: true,
    language: "hi",
    createdAt: "2024-01-15",
  },
  {
    id: "w2",
    name: "Priya Sharma",
    email: "priya@example.com",
    phone: "+91 98765 43211",
    role: "worker",
    skills: ["Cleaning", "Housekeeping", "Cooking"],
    location: "Delhi",
    hourlyRate: 40,
    dailyRate: 400,
    bio: "Experienced housekeeper. Professional and trustworthy.",
    workPhotos: ["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400"],
    rating: 4.9,
    completedJobs: 234,
    streak: 25,
    level: "gold",
    totalEarnings: 380000,
    verified: true,
    language: "en",
    createdAt: "2023-08-20",
  },
];

export const mockPayments: Payment[] = [
  {
    id: "p1",
    jobId: "1",
    amount: 7500,
    status: "pending",
    dueDate: "2025-11-30",
  },
  {
    id: "p2",
    jobId: "2",
    amount: 4000,
    status: "paid",
    dueDate: "2025-11-20",
    paidDate: "2025-11-20",
  },
  {
    id: "p3",
    jobId: "3",
    amount: 8000,
    status: "pending",
    dueDate: "2025-12-05",
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "e1",
    title: "Construction - Sector 62",
    start: "2025-11-27T09:00:00",
    end: "2025-11-27T18:00:00",
    jobId: "1",
    color: "#FF9933",
  },
  {
    id: "e2",
    title: "Plumbing - Koramangala",
    start: "2025-11-28T10:00:00",
    end: "2025-11-28T17:00:00",
    jobId: "3",
    color: "#000080",
  },
  {
    id: "e3",
    title: "Delivery Shift",
    start: "2025-11-29T08:00:00",
    end: "2025-11-29T16:00:00",
    jobId: "2",
    color: "#138808",
  },
];
